### ISSUE TITLE
Fix incompatibilities with kfp-tekton python package

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-sdk#128]
Attempting to pip install both codeflare-sdk and kfp-tekton results in pip conflicts. We should resolve these conflicts so that the stacks can be run alongside each other.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
codeflare-sdk 0.4.3 requires kubernetes==26.1.0, but you have kubernetes 25.3.0 which is incompatible.
openshift 0.11.0 requires kubernetes~=11.0, but you have kubernetes 25.3.0 which is incompatible.
thoth-common 0.36.6 requires kubernetes~=11.0.0, but you have kubernetes 25.3.0 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kfp 1.8.21 requires kubernetes<26,>=8.0.0, but you have kubernetes 26.1.0 which is incompatible.
openshift 0.11.0 requires kubernetes~=11.0, but you have kubernetes 26.1.0 which is incompatible.
thoth-common 0.36.6 requires kubernetes~=11.0.0, but you have kubernetes 26.1.0 which is incompatible.
Successfully installed kubernetes-26.1.0
```

Slack thread: https://project-codeflare.slack.com/archives/C04LK0G441F/p1684936673880639

**Comment by Tomcli** [comment]
Our team can contribute to the upstream project to bump up the k8s client version. Can you open the issue at https://github.com/kubeflow/kfp-tekton/issues so we can track which team needs this fix?

Also which version you want us to upgrade to? is `kubernetes<28,>=8.0.0` good enough for now?

**Comment by Tomcli** [comment]
Okay seems like the python client is only up to 1.26.1 right now. So the best we can do now is upgrade to `kubernetes<27,>=8.0.0` as the end to end test won't able to tell what critical changes will come in the k8s 1.27 python client.

**Comment by anishasthana** [comment]
cc @MichaelClifford @rimolive @Maxusmusti 
@Tomcli Thanks for connecting -- we will reach out shortly.

**Comment by Maxusmusti** [comment]
Sorry for the delay, we are releasing a new version of the SDK with `kubernetes>=25.3.0,<27` if that works

**Comment by Maxusmusti** [comment]
@Tomcli any update on when the next release on the KFP side will be (if your change isn't already in at this point)? Hopefully this SDK release will be by EOD today

**Comment by Tomcli** [comment]
> @Tomcli any update on when the next release on the KFP side will be (if your change isn't already in at this point)? Hopefully this SDK release will be by EOD today

My PR is merged already. I will ping the community to see when they will release the SDK for the kfp v1 release>
https://github.com/kubeflow/pipelines/commit/1d2e26cb1e642c2ac62e746799a24fcef6da91ae

The same commit already in the kfp v2 sdk release today, so going forward this issue should be resolved when we have kfp-tekton v2 in the next kubeflow 1.8 release.
