### ISSUE TITLE
"Permission denied" error when not using the default namespace in hf_interactive notebook

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#129]
I've noticed the below permissions error while running the `hf_interactive.ipynb` notebook demo. 

This error occurs when I deploy my RayCluster in any namespace besides the default namespace. Simply using default overcomes the permissions issue. However, this is not behavior we want to support. We need to ensure that the actions of the codeflare-sdk have the required permissions in the correct namespaces.

![image](https://github.com/project-codeflare/codeflare-sdk/assets/4494906/f815899c-c488-4dec-9899-497897c2ba3d)
![image](https://github.com/project-codeflare/codeflare-sdk/assets/4494906/ab94086b-2caa-450e-8179-7d4fb064c1b6)

This issue can be partially circumvented by adding  `runtime_env = "env_vars": {"HF_HOME":"huggingface"}` to your `ray.init()` command, however, it will just lead to a similar permission issue later on in training.  
 
How can we ensure that the users have the correct permissions in their namespaces?

**Comment by KPostOffice** [comment]
Is this connected to https://github.com/project-codeflare/codeflare-sdk/issues/125 ?

**Comment by KPostOffice** [comment]
I was able to get the `hf_interactive` notebook working using the following Dockerfile

```docker
FROM ghcr.io/foundation-model-stack/base:ray2.1.0-py38-gpu-pytorch1.12.0cu116-20221213-193103

USER 0

RUN chgrp -R 0 /home/ray && chmod -R g+rwX /home/ray
```

which is available at quay.io/kpostlet/ray:2.1.0 if anyone else wants to use this for testing you can pass it to your `ClusterConfiguration` with the `image` parameter.

```python
cluster = Cluster(ClusterConfiguration(
    ...,
    image='quay.io/kpostlet/ray:2.1.0'
))
```

**Comment by KPostOffice** [comment]
This was added but reverted in the ray project. See https://github.com/ray-project/ray/issues/32025 for discussion

**Comment by KPostOffice** [comment]
My current ideas are that we can either:
1. host a custom image with the correct permissions in the home directory
2. run pods with ray user (I think this is UID=1000)
