### ISSUE TITLE
KubeRay Road Map and API Investigation

### ISSUE THREAD

**Issue by Maxusmusti** [project-codeflare/codeflare-sdk#138]
Follow up with AnyScale/KubeRay team to understand supported interfaces and future road map

Additionally, investigate more about the additions and drawbacks of the community-supported KubeRay API Server

**Comment by MichaelClifford** [comment]
Met with the KubeRay/Anyscale team. They are supportive of us contributing to the development of either the KubeRay API Server and/or the KubeRay Python SDK.

Next steps for us are to evaluate the existing  KubeRay SDK and API Server code bases and come up with a plan for contributing.

**Comment by MichaelClifford** [comment]
We have decided to support the KubeRay API server moving forward. Next steps are being tracked here: https://github.com/project-codeflare/codeflare-operator/issues/179
