### ISSUE TITLE
CLI Architecture Document 

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#159]
We need a document that details the desired architecture for the CodeFlare  SDK. 

This task depends on #158 being complete.

**Comment by carsonmh** [comment]
https://docs.google.com/document/d/1f8b5jWhbatbhjuJaPKon56Hq_4R4-TK1Th7I9NN_hFg/edit

**Comment by carsonmh** [comment]
#253
