### ISSUE TITLE
Add support for specifying a cluster CA certificate to the sdk

### ISSUE THREAD

**Issue by accorvin** [project-codeflare/codeflare-sdk#161]
We currently [support](https://github.com/project-codeflare/codeflare-sdk/blob/3b41a22dec1b2471bdc46d8679dae6a85eb96b39/src/codeflare_sdk/cluster/auth.py#LL60C33-L60C33) the `skip_tls` argument in the SDK authentication object for clusters with untrusted CA certificates. This is fine for development purposes, but will be unacceptable for production workloads for most customers.

We should update the SDK to allow specifying the path to a CA certificate bundle so that the auth endpoint can be trusted.

I think we could additionally auto configure trust of the cluster based on where we can expect the cluster CA cert to be stored on disk when running in an openshift pod.

**Comment by Bobbins228** [comment]
Closing this as I have opened another issue relating to authentication via Kubernetes instead of OpenShift. #185

**Comment by Bobbins228** [comment]
Closing this as I have opened another issue relating to authentication via Kubernetes instead of OpenShift. https://github.com/project-codeflare/codeflare-sdk/issues/185
