### ISSUE TITLE
Support the use of Ray Jobs in the SDK

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#177]

**Comment by tedhtchang** [comment]
Do you mean using the [JobSubmissionClient.submit_job](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/doc/ray.job_submission.JobSubmissionClient.submit_job.html#ray.job_submission.JobSubmissionClient.submit_job) to submit ray jobs ?

**Comment by MichaelClifford** [comment]
Yes, something like that. Right now all jobs go through TorchX

**Comment by anishasthana** [comment]
Will follow up later to clarify if this is urgent. If required, will be pulled into sprint 4

**Comment by Bobbins228** [comment]
Closing this as Ray Job Submission was added with #415
