### ISSUE TITLE
Support use of PriorityClass for Appwrappers in the SDK 

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#182]
One feature of MCAD is that is allows for priority and preemption of jobs. The SDK needs to support this feature by allowing a user to define a priority that updates both the priorityClassName and the spec priority that gets added to the generated appwrapper (see this PR for an example AppWrapper #96).

However, the priorityClassNames are non-standard and will be defined and occasionally edited by the cluster admin, therefore the SDK needs to lookup the available priorityClassNames available on the cluster and expose them to the user so that they can use the correct priority class, and raise an error when they try to use on that's not available. 

The SDK also need to handle the case where there are no relevant priority classes on the cluster.

**Comment by Maxusmusti** [comment]
Updated in: #337
