### ISSUE TITLE
Ray Cluster Retrieval Function

### ISSUE THREAD

**Issue by Maxusmusti** [project-codeflare/codeflare-sdk#183]
Add a function to retrieve ray cluster objects from K8s/OCP, so that people can pick up and resume managing the cluster in fire-and-forget or pipeline scenarios.

**Comment by Maxusmusti** [comment]
Some implementation details:

In the `cluster/cluster.py` file, we need a new function:
```
cluster_retrieval(cluster_name: str, namespace: str = "default") -> Cluster:
    This function should search the k8s/OCP cluster using the specified namespace for a RayCluster with the passed-in 
    name. If found, populate and return a Cluster object with all expected fields (via a ClusterConfig). If not, either return
    None or raise some form of "not found" error or exception.
```

Note that cluster_retrieval is a place holder name, and if anything better is come up with, it can be used instead.

**Comment by MichaelClifford** [comment]
@Maxusmusti is there any issue with using the name `get_cluster(cluster_name)` instead?

**Comment by Maxusmusti** [comment]
@MichaelClifford Nope, already a better suggestion 😅
