### ISSUE TITLE
Typo "additionall" Instead of "additional" in the Demo Notebooks

### ISSUE THREAD

**Issue by jbusche** [project-codeflare/codeflare-sdk#197]
There's a small typo in the Demo Notebooks.  Might be a good first issue for someone.

`grep -R additionall *`
```
demo-notebooks/guided-demos/3_basic_interactive.ipynb:    "#install additionall libraries that will be required for model training\n",
demo-notebooks/guided-demos/notebook-ex-outputs/3_basic_interactive.ipynb:    "#install additionall libraries that will be required for model training\n",
demo-notebooks/interactive/hf_interactive.ipynb:    "#install additionall libraries that will be required for this training\n",
```

**Comment by vaibssingh** [comment]
Hey @jbusche, can I take this up?
Since I don't see any documentation on how to contribute, I will be forking the repo and creating a PR from a fix branch to this repo. Is that okay?

**Comment by jbusche** [comment]
Hi @vaibssingh, that sounds great... thanks!  Let me know if you have any troubles or questions, will try to help.

**Comment by vaibssingh** [comment]
@jbusche PR created. Let me know if there is anything else needed before you can merge it :)
