### ISSUE TITLE
Consider update custom notebook incompatible python packages 

### ISSUE THREAD

**Issue by tedhtchang** [project-codeflare/codeflare-sdk#210]
Some of the packages in the [requirement.txt](https://github.com/project-codeflare/codeflare-sdk/blob/main/custom-nb-image/requirements.txt) have dependencies on old python packages which  should be updated to newer version.
Packages to be updated:
```
thoth-python*
openshift
```

They cause errors like below:
https://github.com/project-codeflare/codeflare-sdk/actions/runs/5479520280/jobs/9981464543#step:13:672
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thoth-python 0.16.11 requires beautifulsoup4==4.6.3, but you have beautifulsoup4 4.11.1 which is incompatible.
thoth-common 0.36.6 requires kubernetes~=11.0.0, but you have kubernetes 24.2.0 which is incompatible.
openshift 0.11.0 requires kubernetes~=11.0, but you have kubernetes 24.2.0 which is incompatible.
```
https://github.com/project-codeflare/codeflare-sdk/actions/runs/5479520280/jobs/9981464543#step:13:842
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thoth-common 0.36.6 requires kubernetes~=11.0.0, but you have kubernetes 26.1.0 which is incompatible.
openshift 0.11.0 requires kubernetes~=11.0, but you have kubernetes 26.1.0 which is incompatible.
```

**Comment by tedhtchang** [comment]
@Fiona-Waters Those  ERRORs are output of running this [step](https://github.com/project-codeflare/codeflare-sdk/blob/cf0f990a323eadbf7ff23236d8b4ff30c7cee44b/custom-nb-image/Dockerfile#L20) of the command `cd custom-nb-image; docker build --build-arg SDK_VERSION="0.5.0" -t quay.io/project-codeflare/notebook:v0.5.0 .` The effect is unknown for these incompatible packages.

**Comment by Fiona-Waters** [comment]
Thanks @tedhtchang ! I've done that and created a draft [PR](https://github.com/project-codeflare/codeflare-sdk/pull/275).  Is there any way to test this other than to run the release action, to check if these errors are removed?

**Comment by Fiona-Waters** [comment]
Closing this issue as won't do -  dependencies will be updated with new notebook base image and do not need to be updated now. See [thread](https://project-codeflare.slack.com/archives/C04LK0G441F/p1691070858650619).
