### ISSUE TITLE
Support use of ingress for accessing ray dashboard when ray cluster is created. 

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#219]
The current implementation of "cluster.up()" generates a route resource to expose the ray dashboard to the internet. However, routes are specific to OpenShift and not  available in vanilla kubernetes. We should add support for using ingress resources as well which can be used with kubernetes. 

  
This should also address the issue here:
https://github.com/project-codeflare/codeflare-sdk/issues/143#issuecomment-1615279300

**Comment by Maxusmusti** [comment]
Note that our `cluster.cluster_dashboard_uri()` should then also utilize the ingress API as opposed to the routes API (similar to what is being done currently in `cluster.local_client_url()`

**Comment by tedhtchang** [comment]
Hi @Bobbins228 I think we should use the template to create ingress. Also, the route cr should be removed from the generated appwrapper yaml because of the route CRD is not supported in a K8s cluster.
