### ISSUE TITLE
feature: Copy 'cluster' object definition to new object called 'job'

### ISSUE THREAD

**Issue by clubanderson** [project-codeflare/codeflare-sdk#265]
We, at KubeStellar, are working on enabling multi-cluster job distribution to MCAD.  MCAD will supply an AppWrapper (the '**what**') and an exact cluster identifier (name or uuid) as to '**where**' a job (Ray, PyTorch, spark, etc.) should be run. KubeStellar takes, as input, the 'what' (AppWrapper) and the 'where' (cluster identifier) in the form of an EdgePlacement object.  The EdgePlacement object is picked up by the target cluster's 'mailbox'.  The KubeStellar syncer, that is running on the target cluster where the job should be executed, pulls the workload object (appwrapper) from its associated mailbox.  The AppWrapper is applied to the MCAD agent on the local kubernetes platform (ROKS/OCP in this case).   

taking a step back, further up the stack, MCAD receives instructions on 'what' jobs to execute from KubeFlow via Codeflare SDK.  Jobs are defined by Codeflare SDK using the 'cluster' object definition.  This 'cluster' object ties 1 job to 1 cluster.  For the future we would like codeflare to be able to define a job, but not select a cluster.  To do this we believe we can re-use the 'cluster' object definition, however, the naming will not match up with the expectation of the object.  Why use a cluster object to define a job when there will be no cluster defined in the object? 

To that point, can we have a copy of the cluster object definition and simply rename this copy to be 'job'?  This allows us to define a job without assigning to a cluster.  MCAD will take the job object and convert to appwrapper and further assign a cluster of its choosing.

@chcost am I missing any details that you think should be added to help in understanding our request?

**Comment by asm582** [comment]
@clubanderson Thanks for creating the issue, can we request an ADR?

**Comment by clubanderson** [comment]
what is an ADR?

**Comment by clubanderson** [comment]
Ok. I will look into this. Thank you

**Comment by clubanderson** [comment]
Strategy has changed a bit. Going to close this for now.
