### ISSUE TITLE
Avoid You have reached your pull rate limit error

### ISSUE THREAD

**Issue by tedhtchang** [project-codeflare/codeflare-sdk#324]
### Describe the Bug
The image pull limit reach sometimes restrict users from running ray notebooks. Need to update the image in the [basice-template](https://github.com/project-codeflare/codeflare-sdk/tree/main/src/codeflare_sdk/templates) to use quay.

### Codeflare Stack Component Versions
Please specify the component versions in which you have encountered this bug.

Codeflare SDK:
MCAD:
Instascale:
Codeflare Operator:
Other: 

### Steps to Reproduce the Bug

Ran notebok https://github.com/project-codeflare/codeflare-sdk/blob/main/demo-notebooks/guided-demos/2_basic_jobs.ipynb
Failed to pull image "busybox:1.28": rpc error: code = Unknown desc = reading manifest 1.28 in docker.io/library/busybox: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

### What Have You Already Tried to Debug the Issue?

Yes

### Expected Behavior

A clear and concise description of what you expected to happen instead.

### Screenshots, Console Output, Logs, etc.

The ray cluster failed to start
```
oc get pods                                 api.jimmed.cp.fyre.ibm.com: Fri Aug 25 15:27:16 2023

NAME                    READY  STATUS         RESTARTS  AGE
jobtest-head-h57v2             1/1   Running         0	   4m24s
jobtest-worker-small-group-jobtest-gzztj  0/1   Init:ImagePullBackOff  0	   4m24s
jobtest-worker-small-group-jobtest-wft9m  0/1   Init:ImagePullBackOff  0	   4m24s
```

### Affected Releases

List any release versions, git commit hashes, or git tags, etc. that you know show the bug. If it is the latest `HEAD` on `main`, just put that.

### Additional Context

Add as applicable and when known:

* OS: 1) MacOS, 2) Linux, 3) Windows: [1 - 3]
* OS Version: [e.g. RedHat Linux X.Y.Z, MacOS Monterey, ...]
* Browser (UI issues): 1) Chrome, 2) Safari, 3) Firefox, 4) Other (describe):  [1 - 4 + description?]
* Browser Version (UI issues): [e.g. Firefix 97.0]
* Cloud: 1) AWS, 2) IBM Cloud, 3) Other (describe), or 4) on-premise: [1 - 4 + description?]
* Kubernetes: 1) OpenShift, 2) Other K8s [1 - 2 + description]
* OpenShift or K8s version: [e.g. 1.23.1]
* Other relevant info

Add any other information you think might be useful here.

**Comment by jbusche** [comment]
OK - I think that would do it - if we modify all the image: busybox:1.28 to [quay.io/quay/busybox:latest](http://quay.io/quay/busybox:latest) in https://github.com/project-codeflare/codeflare-sdk, then pulling and using the codeflare-sdk, won't run into this docker rate limit issue.

**Comment by jbusche** [comment]
Have created [PR 330](https://github.com/project-codeflare/codeflare-sdk/pull/330) to address the issue - testing now.

**Comment by jbusche** [comment]
I found it easier to just start brand new with [PR 402](https://github.com/project-codeflare/codeflare-sdk/pull/402) - testing is looking good - ready for review.

**Comment by jbusche** [comment]
Completed
