### ISSUE TITLE
Cluster admin permissions needed for creating ingresses

### ISSUE THREAD

**Issue by Bobbins228** [project-codeflare/codeflare-sdk#400]
### Describe the Bug
Right now cluster admin privileges are needed in order to create ingresses and gather domain names on OpenShift.
This is causing an issue where the `isOpenshift()` function will throw this error 
```ingress_domain is invalid. For Kubernetes Clusters please specify an ingress domain```

### Codeflare Stack Component Versions
Please specify the component versions in which you have encountered this bug.

Codeflare SDK: 0.12.0

### Steps to Reproduce the Bug

1. Create a ray cluster while authenticated as a regular user

### Expected Behavior

Ray clusters should be created in OpenShift without throwing the `ingress_domain is invalid. For Kubernetes Clusters please specify an ingress domain` error.

### Affected Releases

v0.12.0, v0.11.0

**Comment by tedhtchang** [comment]
some conversation is here https://project-codeflare.slack.com/archives/C04LK0G441F/p1699627362015349
