### ISSUE TITLE
Upgrade to v1 RayCluster API 

### ISSUE THREAD

**Issue by astefanutti** [project-codeflare/codeflare-sdk#439]
## WHY

The SDK currently relies on v1alpha1 RayCluster API. This version is deprecated and planned to be removed in KubeRay v1.2.0.

## HOW

The SDK should migrate to using v1 RayCluster API, which is mostly compatible.

## TESTS

Running the e2e tests guarantee non-regression.

**Comment by Bobbins228** [comment]
Resolved in #448
