### ISSUE TITLE
PR title from Codeflare-sdk notebook sync is little misleading

### ISSUE THREAD

**Issue by harshad16** [project-codeflare/codeflare-sdk#472]
### Describe the Bug

PR title from Codeflare-sdk notebook sync is a little misleading
Currently, the Title from the automated PR, says `Digest Updater` which is kinda used for the Notebook Workflow,
https://github.com/opendatahub-io/notebooks/pull/436
it misleads the team, as it constitutes to the manifest updates, 
where this workflow is for the update of Pipfile.

Can we update it to something specific?: 

"[Codeflare Action] Update notebook's pipfile to sync with Codeflare-SDK release ${{ env.CODEFLARE_RELEASE_VERSION }}"
at the line:
https://github.com/project-codeflare/codeflare-sdk/blob/de6cdd57df3269105b2a199af31eaf3332a060bb/.github/workflows/odh-notebooks-sync.yml#L122C22-L122C107

### Codeflare Stack Component Versions
Please specify the component versions in which you have encountered this bug.

Other: [workflow](https://github.com/project-codeflare/codeflare-sdk/blob/main/.github/workflows/odh-notebooks-sync.yml)

### Steps to Reproduce the Bug

Not a bug error.

### What Have You Already Tried to Debug the Issue?

Not required for this one.

### Expected Behavior

concise description of workflow PR template.

### Additional Context

Also this line is not needed in PR description: https://github.com/project-codeflare/codeflare-sdk/blob/de6cdd57df3269105b2a199af31eaf3332a060bb/.github/workflows/odh-notebooks-sync.yml#L128

**Comment by anishasthana** [comment]
cc @sutaakar @abhijeet-dhumal

**Comment by abhijeet-dhumal** [comment]
I'll correct those changes as per your suggestion. Thank you @harshad16 for these insightful corrections.

**Comment by abhijeet-dhumal** [comment]
@harshad16 @sutaakar Please review changes here : https://github.com/project-codeflare/codeflare-sdk/pull/473

**Comment by harshad16** [comment]
Thank you for the work @abhijeet-dhumal :100: :medal_military:
