### ISSUE TITLE
Write "Getting Started" docs

### ISSUE THREAD

**Issue by MichaelClifford** [project-codeflare/codeflare-sdk#54]
As a newcomer to codeflare-sdk I would like a simple to follow readme for how to get started using the tool. 

- [x]  Getting started doc. 
- [x] Getting started doc for user on Open Data Hub.

**Comment by accorvin** [comment]
@MichaelClifford I've created the new ODH repository to house this here: https://github.com/opendatahub-io/distributed-workloads

**Comment by MichaelClifford** [comment]
closed by https://github.com/opendatahub-io/distributed-workloads/pull/1
