### ISSUE TITLE
SDK Authentication Rework

### ISSUE THREAD

**Issue by Maxusmusti** [project-codeflare/codeflare-sdk#67]
Tying log in/out to cluster up/down creates unnecessary difficulty/confusion for users. Separating authentication from cluster management (as well as figuring out auto-auth in ODH/RHODS) would be a solid improvement for usability, clarity, and error-handling.

**Comment by KPostOffice** [comment]
@Maxusmusti I think this was solved with https://github.com/project-codeflare/codeflare-sdk/pull/69
